/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../../../graphql/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  Role: "FREE" | "SUBSCRIBED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Mutation: {};
  Query: {};
  Task: { // root type
    createdAt?: string | null; // String
    description?: string | null; // String
    id?: string | null; // String
    status?: string | null; // String
    title?: string | null; // String
  }
  User: { // root type
    email?: string | null; // String
    id?: string | null; // String
    image?: string | null; // String
    name?: string | null; // String
    role?: NexusGenEnums['Role'] | null; // Role
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createTask: NexusGenRootTypes['Task']; // Task!
    deleteTask: NexusGenRootTypes['Task'] | null; // Task
    updateTask: NexusGenRootTypes['Task'] | null; // Task
  }
  Query: { // field return type
    task: NexusGenRootTypes['Task'] | null; // Task
    tasks: Array<NexusGenScalars['NEXUS__UNKNOWN__TYPE'] | null>; // [NEXUS__UNKNOWN__TYPE]!
    user: NexusGenRootTypes['User'] | null; // User
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  Task: { // field return type
    createdAt: string | null; // String
    description: string | null; // String
    id: string | null; // String
    status: string | null; // String
    title: string | null; // String
    user: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  User: { // field return type
    email: string | null; // String
    id: string | null; // String
    image: string | null; // String
    name: string | null; // String
    role: NexusGenEnums['Role'] | null; // Role
    tasks: Array<NexusGenRootTypes['Task'] | null> | null; // [Task]
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createTask: 'Task'
    deleteTask: 'Task'
    updateTask: 'Task'
  }
  Query: { // field return type name
    task: 'Task'
    tasks: 'NEXUS__UNKNOWN__TYPE'
    user: 'User'
    users: 'User'
  }
  Task: { // field return type name
    createdAt: 'String'
    description: 'String'
    id: 'String'
    status: 'String'
    title: 'String'
    user: 'User'
  }
  User: { // field return type name
    email: 'String'
    id: 'String'
    image: 'String'
    name: 'String'
    role: 'Role'
    tasks: 'Task'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createTask: { // args
      description: string; // String!
      id?: string | null; // String
      status?: string | null; // String
      title: string; // String!
      userId?: string | null; // String
    }
    deleteTask: { // args
      id: string; // String!
    }
    updateTask: { // args
      description?: string | null; // String
      id: string; // String!
      status?: string | null; // String
      title?: string | null; // String
      userId?: string | null; // String
    }
  }
  Query: {
    task: { // args
      userId: string; // String!
    }
    user: { // args
      email: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}